### ISSUE TITLE
ECCV2020 Unsupervised Indoor Depth Estimation

### ISSUE THREAD

**Issue by niujinshuchong** [amusi/ECCV2020-Code#12]
Paper name: P<sup>2</sup>Net: Patch-match and Plane-regularization for Unsupervised Indoor Depth Estimation
Paper link: https://arxiv.org/pdf/2007.07696.pdf
Code link: https://github.com/svip-lab/Indoor-SfMLearner

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
