### ISSUE TITLE
ECCV 2020 Semantic Segmentation

### ISSUE THREAD

**Issue by charlesCXK** [amusi/ECCV2020-Code#13]
[Paper name]: Bi-directional Cross-Modality Feature Propagation with Separation-and-Aggregation Gate for RGB-D Semantic Segmentation
[Paper link]: https://arxiv.org/abs/2007.09183
[Code link]: https://github.com/charlesCXK/RGBD_Semantic_Segmentation_PyTorch

Thank you very much!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
