### ISSUE TITLE
ECCV2020 Dense RepPoints [Instance Segmentation] [Object Detection]

### ISSUE THREAD

**Issue by ancientmooner** [amusi/ECCV2020-Code#15]
Paper name: Dense RepPoints: Representing Visual Objects with Dense Point Sets
Paper link: https://arxiv.org/pdf/1912.11473.pdf
Code link: https://github.com/justimyhxu/Dense-RepPoints
https://github.com/Scalsol/RepPointsV2

Thanks!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
