### ISSUE TITLE
ECCV 2020 ReID

### ISSUE THREAD

**Issue by automan000** [amusi/ECCV2020-Code#17]
https://arxiv.org/abs/2001.08680
https://github.com/automan000/Camera-based-Person-ReID

**Comment by yu-niu** [comment]
Add one:
Paper: https://arxiv.org/abs/1912.08855
Code: https://github.com/yorkeyao/VehicleX

**Comment by guxinqian** [comment]
Paper: https://arxiv.org/pdf/2007.08434
Code: https://github.com/guxinqian/AP3D

**Comment by amusi** [comment]
感谢分享，均已添加！
