### ISSUE TITLE
ECCV 2020 Freespace Detection

### ISSUE THREAD

**Issue by hlwang1124** [amusi/ECCV2020-Code#19]
Paper name: SNE-RoadSeg: Incorporating Surface Normal Information into Semantic Segmentation for Accurate Freespace Detection
Paper link: http://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123750341.pdf
Code link: https://github.com/hlwang1124/SNE-RoadSeg

**Comment by amusi** [comment]
感谢分享，现已添加！
