### ISSUE TITLE
Dynamic R-CNN: Towards High Quality Object Detection via Dynamic Training

### ISSUE THREAD

**Issue by hkzhang95** [amusi/ECCV2020-Code#2]
## 通用目标检测

Paper name: Dynamic R-CNN: Towards High Quality Object Detection via Dynamic Training
Paper link: [https://arxiv.org/abs/2004.06002](https://arxiv.org/abs/2004.06002)
Code link: [https://github.com/hkzhang95/DynamicRCNN](https://github.com/hkzhang95/DynamicRCNN)

**Comment by amusi** [comment]
感谢分享，现已添加！
