### ISSUE TITLE
Our new work about CNN/image classification

### ISSUE THREAD

**Issue by d-li14** [amusi/ECCV2020-Code#6]
Open source code: https://github.com/d-li14/SAN
The paper is to appear on ArXiv soon.
Thanks!

**Comment by amusi** [comment]
感谢分享，现已添加！

**Comment by d-li14** [comment]
[Update] SAN paper has been released today, together with PSConv. The link is https://arxiv.org/abs/2007.06181. Thanks!

**Comment by amusi** [comment]
好的，已更新！
